spring:
  application:
    name: ShopCraft
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
  datasource: 
    url: jdbc:postgresql://localhost:5432/ShopCraft
    username: divaspathak
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate 
      default_schema: public 
    show-sql: true
  
